"""INIT

Revision ID: 12338a1463c4
Revises: 
Create Date: 2026-03-16 16:01:55.146387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12338a1463c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('did', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.String(), nullable=True),
    sa.Column('lon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('did')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_table('knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_id'), 'knowledge', ['id'], unique=False)
    op.create_table('mqtt_broker_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_url', sa.String(), nullable=False),
    sa.Column('broker_port', sa.Integer(), nullable=False),
    sa.Column('broker_username', sa.String(), nullable=True),
    sa.Column('broker_password', sa.String(), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('client_id_prefix', sa.String(), nullable=False),
    sa.Column('topic_prefix', sa.String(), nullable=False),
    sa.Column('keepalive_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mqtt_broker_config_id'), 'mqtt_broker_config', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('smart_contract_id', sa.String(), nullable=False),
    sa.Column('link_cost', sa.Float(), nullable=False),
    sa.Column('callback_wallet_addresses', sa.String(), nullable=False),
    sa.Column('input_parameters', sa.JSON(), nullable=True),
    sa.Column('knowledge_asset', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('weather_description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'lat', 'lon', name='ux_weather_data_ts_lat_lon')
    )
    op.create_index('ix_weather_data_lat_lon_ts', 'weather_data', ['lat', 'lon', 'timestamp'], unique=False)
    op.create_table('hvac_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('central_unit', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('device_key', sa.String(), nullable=True),
    sa.Column('device_secret_hash', sa.String(), nullable=True),
    sa.Column('device_secret_rotated_at', sa.String(), nullable=True),
    sa.Column('device_revoked_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hvac_units_building_id'), 'hvac_units', ['building_id'], unique=False)
    op.create_index(op.f('ix_hvac_units_device_key'), 'hvac_units', ['device_key'], unique=True)
    op.create_index(op.f('ix_hvac_units_id'), 'hvac_units', ['id'], unique=False)
    op.create_table('predictors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('knowledge_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('model_data', sa.JSON(), nullable=True),
    sa.Column('training_data_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictors_id'), 'predictors', ['id'], unique=False)
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_wallet', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_id'), 'rates', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('default_building_id', sa.Integer(), nullable=True),
    sa.Column('public_key', sa.String(), nullable=True),
    sa.Column('api_base_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('hvac_schedule_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('hvac_unit_id', sa.Integer(), nullable=False),
    sa.Column('start_ts', sa.DateTime(), nullable=False),
    sa.Column('end_ts', sa.DateTime(), nullable=False),
    sa.Column('is_on', sa.Boolean(), nullable=False),
    sa.Column('setpoint', sa.Float(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hvac_unit_id'], ['hvac_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hvac_unit_id', 'start_ts', name='uq_hvac_schedule_hvacunit_start')
    )
    op.create_index('ix_hvac_schedule_bld_hvacunit_start', 'hvac_schedule_intervals', ['building_id', 'hvac_unit_id', 'start_ts'], unique=False)
    op.create_index('ix_hvac_schedule_hvacunit_timerange', 'hvac_schedule_intervals', ['hvac_unit_id', 'start_ts', 'end_ts'], unique=False)
    op.create_index(op.f('ix_hvac_schedule_intervals_id'), 'hvac_schedule_intervals', ['id'], unique=False)
    op.create_table('optimization_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('optimization_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('energy_saving_kwh', sa.Float(), nullable=True),
    sa.Column('baseline_consumption_kwh', sa.Float(), nullable=True),
    sa.Column('optimized_consumption_kwh', sa.Float(), nullable=True),
    sa.Column('environmental_points', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_optimized', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'input_hash', 'output_hash', 'optimization_time', name='uq_optimization_building_input_output_time')
    )
    op.create_index(op.f('ix_optimization_results_building_id'), 'optimization_results', ['building_id'], unique=False)
    op.create_index(op.f('ix_optimization_results_id'), 'optimization_results', ['id'], unique=False)
    op.create_index('ix_optimization_results_input_hash', 'optimization_results', ['input_hash'], unique=False)
    op.create_index(op.f('ix_optimization_results_output_hash'), 'optimization_results', ['output_hash'], unique=False)
    op.create_index(op.f('ix_optimization_results_user_id'), 'optimization_results', ['user_id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('hvac_unit_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('rate_of_sampling', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('central_unit', sa.String(), nullable=True),
    sa.Column('payload_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hvac_unit_id'], ['hvac_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_hvac_unit_id'), 'sensors', ['hvac_unit_id'], unique=False)
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    op.create_table('training_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predictor_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('training_started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('training_completed_at', sa.DateTime(), nullable=True),
    sa.Column('training_status', sa.String(), nullable=False),
    sa.Column('training_metrics', sa.JSON(), nullable=True),
    sa.Column('data_size', sa.Integer(), nullable=True),
    sa.Column('model_parameters', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['predictor_id'], ['predictors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_history_id'), 'training_history', ['id'], unique=False)
    op.create_table('user_buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'building_id', name='_user_building_uc')
    )
    op.create_table('hvac_sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('indoor_temp', sa.Float(), nullable=False),
    sa.Column('outdoor_temp', sa.Float(), nullable=False),
    sa.Column('hvac_operation', sa.Integer(), nullable=False),
    sa.Column('energy_consumption', sa.Float(), nullable=False),
    sa.Column('setpoint_temp', sa.Float(), nullable=True),
    sa.Column('outlet_temp', sa.Float(), nullable=True),
    sa.Column('inlet_temp', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hvac_sensor_data_id'), 'hvac_sensor_data', ['id'], unique=False)
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('measurement_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_id', 'measurement_type', 'timestamp', name='ux_sensor_data_sensor_type_bucket')
    )
    op.create_index(op.f('ix_sensor_data_id'), 'sensor_data', ['id'], unique=False)
    op.create_index('ix_sensor_data_sensor_type_ts', 'sensor_data', ['sensor_id', 'measurement_type', 'timestamp'], unique=False)
    op.create_table('sensor_data_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('measurement_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_raw_id'), 'sensor_data_raw', ['id'], unique=False)
    op.create_index('ix_sensor_data_raw_sensor_ts', 'sensor_data_raw', ['sensor_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensor_data_raw_sensor_ts', table_name='sensor_data_raw')
    op.drop_index(op.f('ix_sensor_data_raw_id'), table_name='sensor_data_raw')
    op.drop_table('sensor_data_raw')
    op.drop_index('ix_sensor_data_sensor_type_ts', table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_id'), table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_index(op.f('ix_hvac_sensor_data_id'), table_name='hvac_sensor_data')
    op.drop_table('hvac_sensor_data')
    op.drop_table('user_buildings')
    op.drop_index(op.f('ix_training_history_id'), table_name='training_history')
    op.drop_table('training_history')
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_hvac_unit_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_optimization_results_user_id'), table_name='optimization_results')
    op.drop_index(op.f('ix_optimization_results_output_hash'), table_name='optimization_results')
    op.drop_index('ix_optimization_results_input_hash', table_name='optimization_results')
    op.drop_index(op.f('ix_optimization_results_id'), table_name='optimization_results')
    op.drop_index(op.f('ix_optimization_results_building_id'), table_name='optimization_results')
    op.drop_table('optimization_results')
    op.drop_index(op.f('ix_hvac_schedule_intervals_id'), table_name='hvac_schedule_intervals')
    op.drop_index('ix_hvac_schedule_hvacunit_timerange', table_name='hvac_schedule_intervals')
    op.drop_index('ix_hvac_schedule_bld_hvacunit_start', table_name='hvac_schedule_intervals')
    op.drop_table('hvac_schedule_intervals')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rates_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_index(op.f('ix_predictors_id'), table_name='predictors')
    op.drop_table('predictors')
    op.drop_index(op.f('ix_hvac_units_id'), table_name='hvac_units')
    op.drop_index(op.f('ix_hvac_units_device_key'), table_name='hvac_units')
    op.drop_index(op.f('ix_hvac_units_building_id'), table_name='hvac_units')
    op.drop_table('hvac_units')
    op.drop_index('ix_weather_data_lat_lon_ts', table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_mqtt_broker_config_id'), table_name='mqtt_broker_config')
    op.drop_table('mqtt_broker_config')
    op.drop_index(op.f('ix_knowledge_id'), table_name='knowledge')
    op.drop_table('knowledge')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
