"""baseline

Revision ID: 6d9c88706d58
Revises: 
Create Date: 2026-05-14 16:33:21.481050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d9c88706d58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('did', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.String(), nullable=True),
    sa.Column('lon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('did')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_table('mqtt_broker_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_url', sa.String(), nullable=False),
    sa.Column('broker_port', sa.Integer(), nullable=False),
    sa.Column('broker_username', sa.String(), nullable=True),
    sa.Column('broker_password', sa.String(), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('client_id_prefix', sa.String(), nullable=False),
    sa.Column('topic_prefix', sa.String(), nullable=False),
    sa.Column('keepalive_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mqtt_broker_config_id'), 'mqtt_broker_config', ['id'], unique=False)
    op.create_table('predictors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('model_data', sa.JSON(), nullable=True),
    sa.Column('training_data_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictors_id'), 'predictors', ['id'], unique=False)
    op.create_table('sensor_units',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('si_symbol', sa.Text(), nullable=True),
    sa.Column('conversion_factor', sa.Float(), nullable=True),
    sa.Column('aggregation_method', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_sensor_units_symbol')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('smart_contract_id', sa.String(), nullable=False),
    sa.Column('link_cost', sa.Float(), nullable=False),
    sa.Column('callback_wallet_addresses', sa.String(), nullable=False),
    sa.Column('input_parameters', sa.JSON(), nullable=True),
    sa.Column('knowledge_asset', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('weather_description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'lat', 'lon', name='ux_weather_data_ts_lat_lon')
    )
    op.create_index('ix_weather_data_lat_lon_ts', 'weather_data', ['lat', 'lon', 'timestamp'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'name', name='uq_floors_building_name')
    )
    op.create_table('hvac_units',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('unit_type', sa.Text(), nullable=False),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('cooling_capacity_kw', sa.Numeric(), nullable=True),
    sa.Column('heating_capacity_kw', sa.Numeric(), nullable=True),
    sa.Column('min_airflow_m3_s', sa.Numeric(), nullable=True),
    sa.Column('max_airflow_m3_s', sa.Numeric(), nullable=True),
    sa.Column('cop', sa.Numeric(), nullable=True),
    sa.Column('eer', sa.Numeric(), nullable=True),
    sa.Column('seer', sa.Numeric(), nullable=True),
    sa.Column('scop', sa.Numeric(), nullable=True),
    sa.Column('device_key', sa.String(), nullable=True),
    sa.Column('device_secret_hash', sa.String(), nullable=True),
    sa.Column('device_secret_rotated_at', sa.String(), nullable=True),
    sa.Column('device_revoked_at', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('connection_status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'name', name='uq_hvac_units_building_name')
    )
    op.create_index(op.f('ix_hvac_units_building_id'), 'hvac_units', ['building_id'], unique=False)
    op.create_index(op.f('ix_hvac_units_device_key'), 'hvac_units', ['device_key'], unique=True)
    op.create_index(op.f('ix_hvac_units_id'), 'hvac_units', ['id'], unique=False)
    op.create_table('hvac_zones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('zone_type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'name', name='uq_hvac_zones_building_name')
    )
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_wallet', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_type', sa.String(length=32), server_default='service_quality', nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_id'), 'rates', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('billing_cycle', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='EUR', nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_service_id'), 'subscription_plans', ['service_id'], unique=False)
    op.create_table('thermostats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('external_bms_id', sa.Text(), nullable=True),
    sa.Column('is_controllable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'name', name='uq_thermostats_building_name')
    )
    op.create_table('training_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predictor_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('training_started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('training_completed_at', sa.DateTime(), nullable=True),
    sa.Column('training_status', sa.String(), nullable=False),
    sa.Column('training_metrics', sa.JSON(), nullable=True),
    sa.Column('data_size', sa.Integer(), nullable=True),
    sa.Column('model_parameters', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['predictor_id'], ['predictors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_history_id'), 'training_history', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='registered', nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('default_building_id', sa.Integer(), nullable=True),
    sa.Column('public_key', sa.String(), nullable=True),
    sa.Column('api_base_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_nonce_ts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('auth_audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('device_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['hvac_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auth_audit_log_created_at', 'auth_audit_log', ['created_at'], unique=False)
    op.create_index('idx_auth_audit_log_event_type', 'auth_audit_log', ['event_type'], unique=False)
    op.create_index('idx_auth_audit_log_user_id', 'auth_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_auth_audit_log_id'), 'auth_audit_log', ['id'], unique=False)
    op.create_table('device_commands',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hvac_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('command_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('issued_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('issued_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hvac_unit_id'], ['hvac_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_commands_hvac_unit_id'), 'device_commands', ['hvac_unit_id'], unique=False)
    op.create_index(op.f('ix_device_commands_id'), 'device_commands', ['id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('hvac_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('issued_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hvac_unit_id'], ['hvac_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tokens_hvac_unit_id'), 'device_tokens', ['hvac_unit_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_device_tokens_jti'), 'device_tokens', ['jti'], unique=True)
    op.create_table('hvac_control_models',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('thermostat_id', sa.BigInteger(), nullable=True),
    sa.Column('hvac_unit_id', sa.BigInteger(), nullable=True),
    sa.Column('model_type', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calibrated_from_ts', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('calibrated_to_ts', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('valid_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hvac_unit_id'], ['hvac_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thermostat_id'], ['thermostats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['hvac_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_input_snapshot_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opt_input_snapshot_batch_building_window', 'optimization_input_snapshot_batches', ['building_id', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_optimization_input_snapshot_batches_building_id'), 'optimization_input_snapshot_batches', ['building_id'], unique=False)
    op.create_index(op.f('ix_optimization_input_snapshot_batches_created_by_user_id'), 'optimization_input_snapshot_batches', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_optimization_input_snapshot_batches_id'), 'optimization_input_snapshot_batches', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_input_snapshot_batches_snapshot_hash'), 'optimization_input_snapshot_batches', ['snapshot_hash'], unique=False)
    op.create_table('request_nonces',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nonce', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_request_nonces_created_at', 'request_nonces', ['created_at'], unique=False)
    op.create_index('idx_request_nonces_user_id', 'request_nonces', ['user_id'], unique=False)
    op.create_index(op.f('ix_request_nonces_id'), 'request_nonces', ['id'], unique=False)
    op.create_index(op.f('ix_request_nonces_nonce'), 'request_nonces', ['nonce'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('floor_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('area_m2', sa.Numeric(), nullable=True),
    sa.Column('volume_m3', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'name', name='uq_rooms_building_name')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_building_id'), 'subscriptions', ['building_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('user_auth_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_user_auth_providers_provider_id')
    )
    op.create_index(op.f('ix_user_auth_providers_id'), 'user_auth_providers', ['id'], unique=False)
    op.create_index(op.f('ix_user_auth_providers_user_id'), 'user_auth_providers', ['user_id'], unique=False)
    op.create_table('user_buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'building_id', name='_user_building_uc')
    )
    op.create_table('user_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_type', sa.String(length=16), nullable=False),
    sa.Column('issued_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_tokens_expires_at', 'user_tokens', ['expires_at'], unique=False)
    op.create_index('idx_user_tokens_revoked_at', 'user_tokens', ['revoked_at'], unique=False)
    op.create_index('idx_user_tokens_user_id', 'user_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_tokens_id'), 'user_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_tokens_jti'), 'user_tokens', ['jti'], unique=True)
    op.create_table('zone_hvac_units',
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('hvac_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('allocation_weight', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['hvac_unit_id'], ['hvac_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['hvac_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('zone_id', 'hvac_unit_id')
    )
    op.create_table('zone_schedules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('valid_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['hvac_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_states',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('measured_temp_c', sa.Numeric(), nullable=True),
    sa.Column('setpoint_c', sa.Numeric(), nullable=True),
    sa.Column('delta_t_c', sa.Numeric(), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(), nullable=True),
    sa.Column('co2_ppm', sa.Numeric(), nullable=True),
    sa.Column('occupancy', sa.Integer(), nullable=True),
    sa.Column('thermostat_id', sa.BigInteger(), nullable=True),
    sa.Column('hvac_unit_id', sa.BigInteger(), nullable=True),
    sa.Column('controller_output_pct', sa.Numeric(), nullable=True),
    sa.Column('hvac_status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hvac_unit_id'], ['hvac_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thermostat_id'], ['thermostats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['hvac_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'ts', name='uq_zone_states_zone_ts')
    )
    op.create_table('zone_thermostats',
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('thermostat_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('control_weight', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['thermostat_id'], ['thermostats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['hvac_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('zone_id', 'thermostat_id')
    )
    op.create_table('optimization_input_snapshot_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_batch_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('sensor_type', sa.String(), nullable=True),
    sa.Column('sensor_value', sa.Float(), nullable=True),
    sa.Column('sensor_timestamp', sa.DateTime(), nullable=True),
    sa.Column('measurement_type', sa.String(), nullable=True),
    sa.Column('sensor_unit', sa.String(), nullable=True),
    sa.Column('weather_timestamp', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('weather_description', sa.String(), nullable=True),
    sa.Column('hvac_interval_id', sa.Integer(), nullable=True),
    sa.Column('hvac_is_on', sa.Boolean(), nullable=True),
    sa.Column('hvac_setpoint', sa.Float(), nullable=True),
    sa.Column('hvac_interval_start', sa.DateTime(), nullable=True),
    sa.Column('hvac_interval_end', sa.DateTime(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('source_label', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_batch_id'], ['optimization_input_snapshot_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_input_snapshot_rows_id'), 'optimization_input_snapshot_rows', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_input_snapshot_rows_row_hash'), 'optimization_input_snapshot_rows', ['row_hash'], unique=False)
    op.create_index(op.f('ix_optimization_input_snapshot_rows_snapshot_batch_id'), 'optimization_input_snapshot_rows', ['snapshot_batch_id'], unique=False)
    op.create_table('optimization_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_batch_id', sa.Integer(), nullable=True),
    sa.Column('optimization_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('energy_saving_kwh', sa.Float(), nullable=True),
    sa.Column('baseline_consumption_kwh', sa.Float(), nullable=True),
    sa.Column('optimized_consumption_kwh', sa.Float(), nullable=True),
    sa.Column('environmental_points', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_optimized', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['snapshot_batch_id'], ['optimization_input_snapshot_batches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'input_hash', 'output_hash', 'optimization_time', name='uq_optimization_building_input_output_time')
    )
    op.create_index(op.f('ix_optimization_results_building_id'), 'optimization_results', ['building_id'], unique=False)
    op.create_index(op.f('ix_optimization_results_id'), 'optimization_results', ['id'], unique=False)
    op.create_index('ix_optimization_results_input_hash', 'optimization_results', ['input_hash'], unique=False)
    op.create_index('ix_optimization_results_output_hash', 'optimization_results', ['output_hash'], unique=False)
    op.create_index(op.f('ix_optimization_results_snapshot_batch_id'), 'optimization_results', ['snapshot_batch_id'], unique=False)
    op.create_index(op.f('ix_optimization_results_user_id'), 'optimization_results', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='EUR', nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_ref', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sensor_type', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('unit_id', sa.BigInteger(), nullable=True),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('thermostat_id', sa.BigInteger(), nullable=True),
    sa.Column('hvac_unit_id', sa.BigInteger(), nullable=True),
    sa.Column('external_sensor_id', sa.Text(), nullable=True),
    sa.Column('external_bms_id', sa.Text(), nullable=True),
    sa.Column('payload_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hvac_unit_id'], ['hvac_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thermostat_id'], ['thermostats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['sensor_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['hvac_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'external_sensor_id', name='uq_sensors_building_external_id'),
    sa.UniqueConstraint('building_id', 'name', name='uq_sensors_building_name')
    )
    op.create_index(op.f('ix_sensors_hvac_unit_id'), 'sensors', ['hvac_unit_id'], unique=False)
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    op.create_index(op.f('ix_sensors_room_id'), 'sensors', ['room_id'], unique=False)
    op.create_index(op.f('ix_sensors_unit_id'), 'sensors', ['unit_id'], unique=False)
    op.create_index(op.f('ix_sensors_zone_id'), 'sensors', ['zone_id'], unique=False)
    op.create_table('zone_rooms',
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['hvac_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('zone_id', 'room_id')
    )
    op.create_table('zone_schedule_intervals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('target_setpoint_c', sa.Numeric(), nullable=True),
    sa.Column('min_setpoint_c', sa.Numeric(), nullable=True),
    sa.Column('max_setpoint_c', sa.Numeric(), nullable=True),
    sa.Column('expected_occupancy', sa.Integer(), nullable=True),
    sa.Column('hvac_mode', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['zone_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sensor_id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('quality', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_id', 'ts', name='uq_sensor_data_sensor_ts')
    )
    op.create_index('idx_sensor_data_building_ts', 'sensor_data', ['building_id', 'ts'], unique=False)
    op.create_index('idx_sensor_data_sensor_ts', 'sensor_data', ['sensor_id', 'ts'], unique=False)
    op.create_index(op.f('ix_sensor_data_id'), 'sensor_data', ['id'], unique=False)
    op.create_table('sensor_data_raw',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sensor_id', sa.BigInteger(), nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('msg_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensor_data_raw_sensor_ts', 'sensor_data_raw', ['sensor_id', 'ts'], unique=False)
    op.create_index(op.f('ix_sensor_data_raw_id'), 'sensor_data_raw', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_data_raw_id'), table_name='sensor_data_raw')
    op.drop_index('idx_sensor_data_raw_sensor_ts', table_name='sensor_data_raw')
    op.drop_table('sensor_data_raw')
    op.drop_index(op.f('ix_sensor_data_id'), table_name='sensor_data')
    op.drop_index('idx_sensor_data_sensor_ts', table_name='sensor_data')
    op.drop_index('idx_sensor_data_building_ts', table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_table('zone_schedule_intervals')
    op.drop_table('zone_rooms')
    op.drop_index(op.f('ix_sensors_zone_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_unit_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_room_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_index(op.f('ix_sensors_hvac_unit_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_optimization_results_user_id'), table_name='optimization_results')
    op.drop_index(op.f('ix_optimization_results_snapshot_batch_id'), table_name='optimization_results')
    op.drop_index('ix_optimization_results_output_hash', table_name='optimization_results')
    op.drop_index('ix_optimization_results_input_hash', table_name='optimization_results')
    op.drop_index(op.f('ix_optimization_results_id'), table_name='optimization_results')
    op.drop_index(op.f('ix_optimization_results_building_id'), table_name='optimization_results')
    op.drop_table('optimization_results')
    op.drop_index(op.f('ix_optimization_input_snapshot_rows_snapshot_batch_id'), table_name='optimization_input_snapshot_rows')
    op.drop_index(op.f('ix_optimization_input_snapshot_rows_row_hash'), table_name='optimization_input_snapshot_rows')
    op.drop_index(op.f('ix_optimization_input_snapshot_rows_id'), table_name='optimization_input_snapshot_rows')
    op.drop_table('optimization_input_snapshot_rows')
    op.drop_table('zone_thermostats')
    op.drop_table('zone_states')
    op.drop_table('zone_schedules')
    op.drop_table('zone_hvac_units')
    op.drop_index(op.f('ix_user_tokens_jti'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_id'), table_name='user_tokens')
    op.drop_index('idx_user_tokens_user_id', table_name='user_tokens')
    op.drop_index('idx_user_tokens_revoked_at', table_name='user_tokens')
    op.drop_index('idx_user_tokens_expires_at', table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_table('user_buildings')
    op.drop_index(op.f('ix_user_auth_providers_user_id'), table_name='user_auth_providers')
    op.drop_index(op.f('ix_user_auth_providers_id'), table_name='user_auth_providers')
    op.drop_table('user_auth_providers')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_building_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_request_nonces_nonce'), table_name='request_nonces')
    op.drop_index(op.f('ix_request_nonces_id'), table_name='request_nonces')
    op.drop_index('idx_request_nonces_user_id', table_name='request_nonces')
    op.drop_index('idx_request_nonces_created_at', table_name='request_nonces')
    op.drop_table('request_nonces')
    op.drop_index(op.f('ix_optimization_input_snapshot_batches_snapshot_hash'), table_name='optimization_input_snapshot_batches')
    op.drop_index(op.f('ix_optimization_input_snapshot_batches_id'), table_name='optimization_input_snapshot_batches')
    op.drop_index(op.f('ix_optimization_input_snapshot_batches_created_by_user_id'), table_name='optimization_input_snapshot_batches')
    op.drop_index(op.f('ix_optimization_input_snapshot_batches_building_id'), table_name='optimization_input_snapshot_batches')
    op.drop_index('ix_opt_input_snapshot_batch_building_window', table_name='optimization_input_snapshot_batches')
    op.drop_table('optimization_input_snapshot_batches')
    op.drop_table('hvac_control_models')
    op.drop_index(op.f('ix_device_tokens_jti'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_hvac_unit_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_device_commands_id'), table_name='device_commands')
    op.drop_index(op.f('ix_device_commands_hvac_unit_id'), table_name='device_commands')
    op.drop_table('device_commands')
    op.drop_index(op.f('ix_auth_audit_log_id'), table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_log_user_id', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_log_event_type', table_name='auth_audit_log')
    op.drop_index('idx_auth_audit_log_created_at', table_name='auth_audit_log')
    op.drop_table('auth_audit_log')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_history_id'), table_name='training_history')
    op.drop_table('training_history')
    op.drop_table('thermostats')
    op.drop_index(op.f('ix_subscription_plans_service_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_rates_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_table('hvac_zones')
    op.drop_index(op.f('ix_hvac_units_id'), table_name='hvac_units')
    op.drop_index(op.f('ix_hvac_units_device_key'), table_name='hvac_units')
    op.drop_index(op.f('ix_hvac_units_building_id'), table_name='hvac_units')
    op.drop_table('hvac_units')
    op.drop_table('floors')
    op.drop_index('ix_weather_data_lat_lon_ts', table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_table('sensor_units')
    op.drop_index(op.f('ix_predictors_id'), table_name='predictors')
    op.drop_table('predictors')
    op.drop_index(op.f('ix_mqtt_broker_config_id'), table_name='mqtt_broker_config')
    op.drop_table('mqtt_broker_config')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
