version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: qoe-postgres
    environment:
      POSTGRES_USER: qoe_user
      POSTGRES_PASSWORD: qoe_password
      POSTGRES_DB: qoe_database
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qoe_user -d qoe_database"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
