# PostgreSQL configuration file for container
# Set the default timezone to UTC for all sessions
listen_addresses = '*'
timezone = 'UTC'
shared_preload_libraries = 'pg_cron'
cron.database_name = 'qoe_database'
