apiVersion: 1
providers:
  - name: Loki
    orgId: 1
    folder: ""
    type: loki
    disableDeletion: false
    editable: true
    options: {}
    secure: true
    secureJsonData:
      # Grafana will store this securely; expand from env if supported by the image
      authorization: ${LOKI_BEARER:-}
    url: ${LOKI_URL:-http://loki:3100}
    access: proxy
    basicAuth: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: "loki"
          matcherRegex: '"(?P<method>GET|POST|PUT|DELETE|PATCH|OPTIONS) (?P<path>[^ ]+) HTTP/[0-9.]+'
          name: http_request
          url: ${LOKI_URL:-http://loki:3100}
