apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: https://logs.nkoutantos.com
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: secure_loki_password_2025
    isDefault: true
    version: 1
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: loki
          matcherRegex: "container_name=\"(.+)\""
          name: "Container Name"
          url: "/explore?orgId=1&left=[\"now-1h\",\"now\",\"Loki\",{\"expr\":\"{container_name=\\\"$${__value.raw}\\\"}\"},{\"mode\":\"Logs\"},{\"ui\":[true,true,true,\"none\"]}]"