# fly.toml file for external-adapter
app = "external-adapter"
primary_region = "fra"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.healthcheck]
    type = "http"
    interval = "15s"
    timeout = "5s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0

    [checks.healthcheck.headers]
      X-Forwarded-Proto = "https"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
