version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.0
    container_name: qoe-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "127.0.0.1:3100:3100"                 # host-only, Caddy will proxy
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    restart: unless-stopped
    networks:
      - qoe-logging-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:10.1.0
    container_name: qoe-grafana
    env_file:
      - .env
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      GF_SERVER_ROOT_URL: "https://${GRAFANA_DOMAIN:-grafana.nkoutantos.com}"
    ports:
      - "127.0.0.1:4000:3000"                 # host-only, Caddy will proxy
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    networks:
      - qoe-logging-network
    depends_on:
      loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  alloy:
    image: grafana/alloy:1.4.1
    container_name: qoe-alloy
    command: ["run", "--config.format=promtail", "--config.expand-env", "--server.http.listen-addr=0.0.0.0:12345", "/etc/alloy/promtail.yaml"]
    env_file:
      - .env
    ports:
      - "127.0.0.1:12345:12345"                   
    volumes:
      - ./alloy-config.yaml:/etc/alloy/promtail.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy_tmp:/tmp
    restart: unless-stopped
    networks:
      - qoe-logging-network
    depends_on:
      loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:12345/-/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  loki_data:
  grafana_data:
  alloy_tmp:

networks:
  qoe-logging-network:
    driver: bridge
