services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qoe-jenkins
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "18081:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins:
