version: '3.8'
services:
  ui:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    env_file:
      - .env
